export const config = {
  // --- API & Auth ---
  DEFAULT_QUERY: 'NOT "react" NOT "next.js" NOT "wix" NOT "HubSpot" NOT "Squarespace" NOT "Webflow Website" NOT "Webflow Page" NOT "Webflow Designer" NOT "Content Marketing" NOT "Guest Post" "CLS" OR "INP" OR "LCP" OR "pagespeed" OR "Page speed" OR "Shopify speed" OR "Wordpress speed" OR "site speed" OR "web vitals" OR "WebPageTest" OR "GTmetrix" OR "Lighthouse scores" OR "Google Lighthouse" OR "page load" OR "performance expert" OR "performance specialist" OR "performance audit"',
  GQL_ENDPOINT_BASE: 'https://www.upwork.com/api/graphql/v1',

  // --- Background Script ---
  ALARM_NAME: 'upwork-job-check',
  FETCH_INTERVAL_MINUTES: 5,
  MAX_SEEN_JOBS: 200,

  // --- Filtering ---
  TITLE_EXCLUSION: [
    'french speaking only',
    'SEO Optimization for',
    'Prestashop Specialist',
    'Framer website',
    'Framer Developer',
    'SEO Specialist Needed for Website Optimization',
    'TikTok Shop',
    'Virtual Assistant',
    'Funnel Expert',
    'BigCommerce Developer',
    'Webflow Developer',
    'Webflow Expert',
    'Webflow SEO',
    'Squarespace Website',
    'Squarespace Blog',
    'Squarespace Developer',
    'Brand Strategist',
    'Product Page Designer',
    'Site Completion and Optimization',
    'Landing Page Developer',
    'Bilingual ENG/SPA',
    'Logo Designer',
    'Graphic Designer',
    'Full Website Redisign',
    'Logo Designer',
    'Unity Performance Specialist',
    'Specialist for TikTok',
    'Spanish Fluent',
  ].map(s => s.toLowerCase()),
  COUNTRY_LOW_PRIORITY: [
    'India',
    'Indonesia',
    'pakistan',
    'Bangladesh',
    'Philippines',
    'Lebanon',
    'Nigeria',
    'IND',
  ].map(s => s.toLowerCase()),
};